# Numpy

## Introduction

Check the [Numpy Documentation](https://numpy.org/devdocs/index.html) for more information.

NumPy's main object is the **homogeneous multidimensional array**.

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

NumPy also includes a wide range of mathematical functions and has a wide range of applications in Data Science and Machine Learning.

## Installing Numpy

If you have `Python` and `PIP` already installed on a system, simply run the following command in the terminal.

```bash
pip install numpy
```

**NOTE:** *Some IDEs such as Anaconda and Google Colab already has Numpy and various other commonly used packages installed.*

## Importing Numpy

We can import Numpy in python using the `import` keyword. Though, Numpy is usually imported under the `np` alias.

In [1]:
import numpy as np

## Creating Numpy Arrays

The array object in NumPy is called `ndarray`.

### Creating from a Python List and Tuple

You can create an Numpy `ndarray` from a regular Python list or tuple using the `array()` function. 

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Creating a Numpy `ndarray` with `np.arange()`

`np.arange()` works almost exactly like the basic python `range()` function.

`np.arange()` function returns an array with values within a specified interval.

In [4]:
arr = np.arange(5)

print(arr)

[0 1 2 3 4]


In [5]:
arr = np.arange(2, 6)

print(arr)

[2 3 4 5]


In [6]:
arr = np.arange(2, 20, 3)

print(arr)

[ 2  5  8 11 14 17]


### Creating a Numpy `ndarray` using `np.linspace()`

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval

In [7]:
arr = np.linspace(0, 10, num=5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


### Creating a Numpy `ndarray` using `np.zeros()` and `np.ones()`

The `np.zeros()` function allows us to create an array filled with all zeros. Similarly, the `np.ones()` function allows us to create an array filled with all ones. You only need to specify the shape of the array in a tuple (or a single positive integer if it is a 1D array).

In [8]:
arr = np.zeros(4)

print(arr)

[0. 0. 0. 0.]


In [9]:
arr = np.ones((2, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


## N-Dimensional Arrays

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

|  1  |  5  |  2  |  0  |
|:---:|:---:|:---:|:---:|

A two-dimensional array would be like a table:

|  1  |  5  |  2  |  0  |
|:---:|:---:|:---:|:---:|
|  8  |  3  |  6  |  1  |
|  1  |  7  |  2  |  9  |

A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages.

NumPy `ndarray` have some restrictions. For instance:

- All elements of the array must be of the same type of data.
- Once created, the total size of the array can't change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.



## Ndarray Attributes

In [10]:
a = np.array([[5, 7, 0],[0, 1, 9]])

print(a)

[[5 7 0]
 [0 1 9]]


### `ndim` Attribute

The number of dimensions of an array is contained in the `ndim` attribute.

In [11]:
a.ndim

2

### `shape` Attribute

The `shape` of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [12]:
a.shape

(2, 3)

### `size` Attribute

The fixed, total number of elements in array is contained in the `size` attribute. This is the product of the elements of the array's shape.

In [13]:
a.size

6

### `dtype` Attribute

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the `dtype` attribute.

In [14]:
a.dtype

dtype('int64')

## Data Types and Casting

NumPy supports many data types such as `int32`, `int64`, `float32`, `float64`, `bool`, and more. You can specify the data type when creating an array, or convert (cast) an existing array to a different type using `.astype()`.

This is useful when you need to control memory usage or prepare data for specific operations.

In [15]:
arr = np.array([1.7, 2.5, 3.9, 4.1, 5.0])
print(arr.dtype)

# Cast from float to integer
arr = arr.astype(np.int64) # decimals are truncated, NOT rounded
print(arr.dtype)
print(arr)

float64
int64
[1 2 3 4 5]


In [16]:
# Cast to boolean
arr = np.array([1, 0, 3, 0, 5])
print(arr.astype(bool))

[ True False  True False  True]


## Indexing and Slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [17]:
# Indexing
arr = np.array([2, 4, 6, 8])

print(arr[2])

6


In [18]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:5])

[3 4 5]


In [19]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:])

[3 4 5 6 7]


In [20]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5])

[1 2 3 4 5]


In [21]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:-2])  # [3 4 5]

[3 4 5]


### Indexing and Slicing in Multidimensional Arrays

When working with multidimensional arrays, there are two common ways to access elements.

You can use nested indexing, which is similar to the one basic python uses.

In [22]:
# This is a two dimensional array
arr = np.array([
    [0, 1, 2, 3], 
    [1, 4, 9, 0],
    [2, 5, 3, 5],
])

print(arr[1][2])

9


However we would much rather use:

In [23]:
# This is a two dimensional array
arr = np.array([
    [0, 1, 2, 3], 
    [1, 4, 9, 0],
    [2, 5, 3, 5],
])

print(arr[1, 2])

9


This way is cleaner and more readable and is computationally faster.

Similarly, we can slice in this way:

In [24]:
# This is a two dimensional array
arr = np.array([
    [0, 1, 2, 3], 
    [1, 4, 9, 0],
    [2, 5, 3, 5],
])

print(arr[1:, 1:3])

[[4 9]
 [5 3]]


## Boolean Indexing

One of NumPy's most powerful features is **boolean indexing**. This is filtering an array by a condition. Instead of specifying index positions, you pass a condition and NumPy returns only the elements where the condition is `True`.

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr > 3) # The condition produces a boolean array

print(arr[arr > 3]) # Use that condition to filter the array

[False False False  True  True  True  True]
[4 5 6 7]


In [26]:
# You can combine conditions with & (and) and | (or)
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Elements greater than 1 AND less than 7 AND even
print(arr[(arr > 1) & (arr < 7) & (arr % 2 == 0)])

[2 4 6]


### `np.where()`

`np.where(condition, value_if_true, value_if_false)` lets you replace values in an array based on a condition. Think of it as a vectorized if-else.

In [27]:
scores = np.array([30, 45, 55, 70, 85, 90])

# Label scores below 60 as 'low', 60 and above as 'high'
labels = np.where(scores < 60, 'low', 'high')
print(labels)

['low' 'low' 'low' 'high' 'high' 'high']


## Flattening and Reshaping

### Flattening

Both `.flatten()` and `.ravel()` methods are used to convert a multidimensional NumPy array into a 1D array.

The key difference is that `.flatten()` returns a **copy** of the array while `.ravel()` returns a **view** where possible.

In [28]:
arr = np.array([
    [[0, 1, 2, 3], 
     [0, 4, 4, 0],
     [3, 3, 3, 3]],

    [[0, 1, 2, 3], 
     [0, 4, 9, 0],
     [3, 3, 3, 3]]
])

flat = arr.flatten()
print(flat)

[0 1 2 3 0 4 4 0 3 3 3 3 0 1 2 3 0 4 9 0 3 3 3 3]


In [29]:
arr = np.array([
    [[0, 1, 2, 3], 
     [0, 4, 4, 0],
     [3, 3, 3, 3]],

    [[0, 1, 2, 3], 
     [0, 4, 9, 0],
     [3, 3, 3, 3]]
])

ravelled = arr.ravel()
print(ravelled)

[0 1 2 3 0 4 4 0 3 3 3 3 0 1 2 3 0 4 9 0 3 3 3 3]


### Reshaping

You can also reshape an array with the `.reshape()` method. Reshaping allows us to change the shape of a NumPy array without changing its data. However the size (i.e total number of elements) **must** remain the same for this to work.

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr = arr.reshape(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


## Copying Arrays

This is one of the most common sources of bugs for NumPy beginners. When you slice a NumPy array, you get a **view**, not a copy. This means changes to the slice will change the original array too.

Use `.copy()` when you want an independent copy.

In [31]:
original = np.array([1, 2, 3, 4, 5])

view = original[1:3]
view[0] = 9

print("Original after modifying view:", original)

Original after modifying view: [1 9 3 4 5]


In [32]:
original = np.array([1, 2, 3, 4, 5])

copy = original[1:3].copy()
copy[0] = 999

print("Original after modifying copy:", original)

Original after modifying copy: [1 2 3 4 5]


## Sorting

`np.sort()` returns a sorted copy of an array. `np.argsort()` returns the **indices** that would sort the array and is useful when you need to know the rank or order of elements.

In [33]:
arr = np.array([3, 1, 4, 5, 2, 7])

sorted_arr = np.sort(arr)

print(sorted_arr)

[1 2 3 4 5 7]


In [34]:
# argsort is useful for sorting one array by the order of another
scores = np.array([85, 60, 90, 95, 70, 100])
names  = np.array(['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'])

order = np.argsort(scores)
print("Indices that sort the array:", order)
print("Names ranked by score:", names[order])

Indices that sort the array: [1 4 0 2 3 5]
Names ranked by score: ['Bob' 'Eve' 'Alice' 'Charlie' 'Diana' 'Frank']


## Stacking and Splitting

You can combine multiple arrays into one, or split one array into several pieces.

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# hstack: stack side by side (horizontally)
print("hstack:\n", np.hstack([a, b]))

# vstack: stack on top of each other (vertically)
print("vstack:\n", np.vstack([a, b]))

# concatenate: general-purpose joining along a specified axis
print("concatenate:\n", np.concatenate([a, b]))

hstack:
 [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]
concatenate:
 [1 2 3 4 5 6]


In [36]:
# split: split an array into equal parts
arr = np.array([1, 2, 3, 4, 5, 6])

parts = np.split(arr, 3)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


## Random Numbers

The `np.random` module lets you generate random numbers and arrays.

Use `np.random.seed()` to make your random results **reproducible**. The same seed always produces the same random numbers.

In [37]:
np.random.seed(42)  # set seed for reproducibility

# Random floats between 0 and 1
print("rand: ", np.random.rand(5))

# Random integers between 0 (inclusive) and 10 (exclusive)
print("randint: ", np.random.randint(0, 10, size=5))

# Random numbers from a standard normal distribution (mean=0, std=1)
print("randn: ", np.random.randn(5))

rand:  [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
randint:  [2 6 7 4 3]
randn:  [ 0.39257975 -0.92918467  0.07983181 -0.1595165   0.02222183]


## Broadcasting

You can perform basic arithmetic operations (addition, subtraction, multiplication and division) with arrays of the same size. Calculations are done elementwise.

In [38]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([9, 8, 7, 6, 5])

print(a + b)

[9 9 9 9 9]


There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar). You can perform this operation with:

In [39]:
arr = np.array([1.0, 2.0])

arr = arr * 1.6

print(arr)

[1.6 3.2]


In [40]:
arr = np.ones((2, 3))

arr += 4

print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


NumPy understands that the operation should happen with each cell. That concept is called broadcasting. The dimensions of your array must be compatible. Two dimensions are compatible when they are equal or when one of them is 1.

Arrays do not need to have the same number of dimensions. Missing dimensions are treated as size 1, and the resulting array takes the shape formed by the largest size in each dimension.

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)

b = np.array([10, 20, 30])  # shape: (3,). Treated as (1, 3) during broadcasting

print(a * b)  # shape of result: (2, 3)

[[ 10  40  90]
 [ 40 100 180]]


## Maths

NumPy is a full library for mathematical operations. It has functions for aggregation, trigonometry, logarithms, linear algebra, and more.

### Aggregation Functions

In [42]:
arr = np.array([1, 2, 3, 4, 5])

print(f"Mean: {np.mean(arr)}")
print(f"Sum: {np.sum(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Std: {np.std(arr)}")
print(f"Median: {np.median(arr)}")

Mean: 3.0
Sum: 15
Min: 1
Max: 5
Std: 1.4142135623730951
Median: 3.0


### Linear Algebra

In [43]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Dot product of two 1D arrays
print(np.dot(a, b))

32


In [44]:
# Matrix multiplication with the @ operator
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

print(A @ B)

[[ 58  64]
 [139 154]]


### Trigonometry and Logarithms

In [45]:
print(np.cos(1))

0.5403023058681398


In [46]:
arr = np.array([1, 2, 3, 4])

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999]


## Axis-Based Operations

Imagine a 2D array. You can apply functions along a specific axis. If `axis=0`, NumPy applies the operation down each column, reducing rows. If `axis=1`, it applies the operation across each row, reducing columns.

In [47]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Array:\n", arr)
print("Sum of each column (axis=0):", np.sum(arr, axis=0))
print("Sum of each row (axis=1):", np.sum(arr, axis=1))

Array:
 [[1 2 3]
 [4 5 6]]
Sum of each column (axis=0): [5 7 9]
Sum of each row (axis=1): [ 6 15]


## Mini Project: Analysing Student Scores

Let's put everything together with a small example. We have test scores for 5 students across 3 subjects and want to compute useful statistics.

In [48]:
# Rows = students, Columns = [Maths, English, Science]
scores = np.array([
    [78, 85, 90], # Alice
    [55, 60, 70], # Bob
    [90, 95, 88], # Charlie
    [40, 50, 45], # Diana
    [88, 76, 95], # Eve
])

names = np.array(['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])

# Average score per student (across columns)
avg_per_student = np.mean(scores, axis=1)

# Average score per subject (across rows)
avg_per_subject = np.mean(scores, axis=0)

# Who passed? (average >= 60)
passed = names[avg_per_student >= 60]
failed = names[avg_per_student < 60]

print("Scores:\n", scores)
print("\nAverage per student:", avg_per_student.round(2))
print("Average per subject:", avg_per_subject.round(2))
print("Highest score overall:", np.max(scores))
print("Students who passed (avg >= 60):", passed)
print("Students who failed:", failed)

Scores:
 [[78 85 90]
 [55 60 70]
 [90 95 88]
 [40 50 45]
 [88 76 95]]

Average per student: [84.33 61.67 91.   45.   86.33]
Average per subject: [70.2 73.2 77.6]
Highest score overall: 95
Students who passed (avg >= 60): ['Alice' 'Bob' 'Charlie' 'Eve']
Students who failed: ['Diana']
