# Numpy

## Introduction

Check the [Numpy Documentation](https://numpy.org/devdocs/index.html) for more information.

NumPy’s main object is the **homogeneous multidimensional array**.

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

NumPy also includes a wide range of mathematical functions and has a wide range of applications in Data Science and Machine Learning.

## Installing Numpy

If you have `Python` and `PIP` already installed on a system, simply run the following command in the terminal.

```bash
pip install numpy
```

**NOTE:** *Some IDEs such as Anaconda and Google Colab already has Numpy and various other commonly used packages installed.*

## Importing Numpy

We can import Numpy in python using the import keyword.

In [1]:
import numpy

Though, Numpy is usually imported under the `np` alias.

In [2]:
import numpy as np

## Creating Numpy Arrays

The array object in NumPy is called `ndarray`.

### Creating from a Python List and Tuple

You can create an Numpy `ndarray` from a regular Python list or tuple using the `array()` function. 

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Creating a Numpy `ndarray` with `np.arange()`

`np.arange()` works almost exactly like the basic python `range()` function.

`np.arange()` function returns an array with values within a specified interval.

In [5]:
arr = np.arange(5)

print(arr)

[0 1 2 3 4]


In [6]:
arr = np.arange(2, 6)

print(arr)

[2 3 4 5]


In [7]:
arr = np.arange(2, 20, 3)

print(arr)

[ 2  5  8 11 14 17]


### Creating a Numpy `ndarray` using `np.linspace()`

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval

In [8]:
arr = np.linspace(0, 10, num=5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


### Creating a Numpy `ndarray` using `np.zeros()` and `np.ones()`

The `np.zeros()` function allows us to create an array filled with all zeros. Similarly, the `np.ones()` function allows us to create an array filled with all ones. You only need to specify the shape of the array in a tuple (or a single positive integer if it is a 1D array).

In [9]:
arr = np.zeros(4)

print(arr)

[0. 0. 0. 0.]


In [10]:
arr = np.ones((2, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


## N-Dimensional Arrays

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

|  1  |  5  |  2  |  0  |
|:---:|:---:|:---:|:---:|

A two-dimensional array would be like a table:

|  1  |  5  |  2  |  0  |
|:---:|:---:|:---:|:---:|
|  8  |  3  |  6  |  1  |
|  1  |  7  |  2  |  9  |

A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages.

NumPy `ndarray` have some restrictions. For instance:

- All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.



## Ndarray Attributes

In [11]:
a = np.array([[5, 7, 0],[0, 1, 9]])

print(a)

[[5 7 0]
 [0 1 9]]


### `ndim` Attribute

The number of dimensions of an array is contained in the `ndim` attribute.

In [12]:
a.ndim

2

### `shape` Attribute

The `shape` of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [13]:
a.shape

(2, 3)

### `size` Attribute

The fixed, total number of elements in array is contained in the `size` attribute. This is the product of the elements of the array’s shape.

In [14]:
a.size

6

### `dtype` Attribute

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the `dtype` attribute.

In [15]:
a.dtype

dtype('int64')

## Indexing and Slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [16]:
# Indexing
arr = np.array([2, 4, 6, 8])

print(arr[2])

6


In [17]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:5])

[3 4 5]


In [18]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:])

[3 4 5 6 7]


In [19]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5])

[1 2 3 4 5]


In [20]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:-2])

[3 4 5]


### Indexing and Slicing in Multidimensional Arrays

When working with multidimensional arrays, there are two common ways to access elements.

You can use nested indexing, which is similar to the one basic python uses.

In [21]:
# This is a two dimensional array
arr = np.array([
    [0, 1, 2, 3], 
    [1, 4, 9, 0],
    [2, 5, 3, 5],
])

print(arr[1][2])

9


However we would much rather use:

In [22]:
# This is a two dimensional array
arr = np.array([
    [0, 1, 2, 3], 
    [1, 4, 9, 0],
    [2, 5, 3, 5],
])

print(arr[1, 2])

9


This way is cleaner and more readable and is computationally faster.

Similarly, we can slice in this way:

In [23]:
# This is a two dimensional array
arr = np.array([
    [0, 1, 2, 3], 
    [1, 4, 9, 0],
    [2, 5, 3, 5],
])

print(arr[1:, 1:3])

[[4 9]
 [5 3]]


## Flattening and Reshaping

### Flattening

Both `.flatten()` and `.ravel()` methods are used to convert a multidimensional NumPy array into a 1D array.

In [24]:
arr = np.array([
    [[0, 1, 2, 3], 
     [0, 4, 4, 0],
     [3, 3, 3, 3]],

    [[0, 1, 2, 3], 
     [0, 4, 9, 0],
     [3, 3, 3, 3]]
])

arr = arr.flatten()

print(arr)

[0 1 2 3 0 4 4 0 3 3 3 3 0 1 2 3 0 4 9 0 3 3 3 3]


In [25]:
arr = np.array([
    [[0, 1, 2, 3], 
     [0, 4, 4, 0],
     [3, 3, 3, 3]],

    [[0, 1, 2, 3], 
     [0, 4, 9, 0],
     [3, 3, 3, 3]]
])

arr = arr.ravel()

print(arr)

[0 1 2 3 0 4 4 0 3 3 3 3 0 1 2 3 0 4 9 0 3 3 3 3]


### Reshaping

You can also reshape an array with the `.reshape()` method. Reshaping allows us to change the shape of a NumPy array without changing its data. However the size (i.e total number of elements) **must** remain the same for this to work.

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr = arr.reshape(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


## Broadcasting

You can before basic arithemetic operations i.e addition, subtraction, multiplication and division with arrays of the same size. Calculations are done elementwise.

In [27]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([9, 8, 7, 6, 5])

print(a + b)

[9 9 9 9 9]


There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar). You can perform this operation with:

In [28]:
arr = np.array([1.0, 2.0])

arr = arr * 1.6 # or arr *= 1.6 if you are feeling fancy.

print(arr)

[1.6 3.2]


In [29]:
arr= np.ones((2, 3))

arr += 4

print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. The dimensions of your array must be compatible. Two dimensions are compatible when they are equal or when one of them is 1.

Arrays do not need to have the same number of dimensions. Missing dimensions are treated as size 1, and the resulting array takes the shape formed by the largest size in each dimension.

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]]) # Size: (2, 3)

b = np.array([10, 20, 30]) # Size: (3,) would be treated as (3, 1)

print(a * b) # resulting size is (2, 3)

[[ 10  40  90]
 [ 40 100 180]]


## Maths

Numpy is also a library for mathematical operations. It has functions for trigonometry, logarithms, statistics and probability, linear algebra e.t.c. 

In [31]:
arr = np.array([1, 2, 3, 4, 5])

print(f"Mean is {np.mean(arr)}")

Mean is 3.0


In [32]:
print(np.cos(1))

0.5403023058681398


In [33]:
arr = np.array([1, 2, 3, 4])
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436]
